name: Deploy to Hostinger FTP

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  ftp-deploy:
    name: FTP Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: ${{ secrets.FTP_SERVER_NET }}
        username: ${{ secrets.FTP_USERNAME_NET }}
        password: ${{ secrets.FTP_PASSWORD_NET }}
        server-dir: public_html/
        protocol: ftps
        port: 21
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          .github/
          README.md
